### ISSUE TITLE
Music for game

### ISSUE THREAD

**Issue by GoatsAreTB** [NoeCoOfficial/Expland#11]
I made some new music for the game more in line with the stuff you were showing me. I tried my best one is a piano which is laid back and chill and the other one is a guitar do with your will you can also edit it on "sound trap" so go check that out Give me some opinions on what I need to do to improve.

[drive-download-20240907T031636Z-001.zip](https://github.com/user-attachments/files/16914178/drive-download-20240907T031636Z-001.zip)

**Comment by GoatsAreTB** [comment]
BTW dose that download thing work?

**Comment by sebashtioon** [comment]
Hey not bad, also yes the drive thing works. Also don't put a number hashtag at the end when submitting an issue because it mentions other issues. This issue number is already #11 btw

**Comment by GoatsAreTB** [comment]
ohhhhhhhhhhhhhhhhhhhhhh...

**Comment by sebashtioon** [comment]
I made a folder for audio in the games files, containing music and SFX, as well as tests. I will implement your songs very soon!
