### ISSUE TITLE
directional spawning error

### ISSUE THREAD

**Issue by GoatsAreTB** [NoeCoOfficial/Expland#12]
In our game when we spawn we always respawn in a set direction. Let us save the player's camera rotation so that when they reenter the game they are looking in the direction you ended the session. This can stop glitches and other issues from arising later down the track. I would appreciate it if you could help with this do you think this is something we should change?
@NoeCoOfficial/founders

**Comment by sebashtioon** [comment]
Yes definitely👍 im onto it
