### ISSUE TITLE
Crouch Mechanic

### ISSUE THREAD

**Issue by GoatsAreTB** [NoeCoOfficial/Expland#8]
Adding a crouch mechanic would be beneficial. I think it could move the player's sight so they see lower and their hit box is smaller, meaning that they could move and go through places with this smaller hit box. There could be some problems like jumping and crouching. For example, you can bypass the decreased speed by jumping or something like that.

**Comment by sebashtioon** [comment]
aight will work on that

**Comment by sebashtioon** [comment]
IT IS DONE
